---
- name: set application facts
  ansible.builtin.set_fact:
    rancher_name: "rancher"
    rancher_compose: "{{ rancher_compose }}"

- name: "Ensure config folders exists"
  ansible.builtin.file:
    name: '{{ rancher_base_path }}/{{ rancher_name }}/{{ item }}'
    owner: "{{ rancher_user }}"
    group: "{{ rancher_group }}"
    mode: "0770"
    state: directory
  with_items:
    - "{{ rancher_sub_path }}"

- name: "create docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ rancher_base_path }}/{{ rancher_name }}/docker-compose.yml"
    mode: "0644"
    owner: "{{ rancher_user }}"
    group: "{{ rancher_group }}"
  notify: restart rancher service

- name: "Create systemd service"
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/{{ rancher_name }}.service"
    mode: "0660"
    owner: "root"
    group: "root"
  notify: reload systemd
